[profile.default]
solc = "0.8.33"
evm_version = "osaka"
via_ir = true
ffi = true
fs_permissions = [
    { access = "read", path = "../huff-router/contracts/v3-artifacts/" },
    { access = "read", path = "out/" }
]
allow_paths = [
    "../huff-router/contracts/lib/evm-contracts/src",
    "../huff-router/contracts/lib/forge-std/src",
    "../huff-router/contracts/lib/solady/src"
]

[fmt]
sort_imports = true
wrap_comments = true

[lint]
lint_on_build = false
exclude = ["src/YulRouter.yul"]
